pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Build Information') {
            steps {
                echo "=================================="
                echo "Branch Name : ${env.BRANCH_NAME}"
                echo "Build Number: ${env.BUILD_NUMBER}"
                echo "Workspace   : ${env.WORKSPACE}"
                echo "=================================="
            }
        }

        stage('verify zowe version') {
            steps {
                  bat '
                        node --version
                        zowe --version
                     '
            }
            
        }

        stage('List Repository Files') {
            steps {
                bat 'dir'
            }
        }

        stage('Detect Changed Files') {
            steps {
                script {
                    def changedFiles = bat(
                        script: '@git diff --name-only HEAD~1 HEAD',
                        returnStdout: true
                        ).trim()

                        echo "=================================="
                        echo "Changed Files:"
                        echo changedFiles
                        echo "=================================="
                }
            }
        }

    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}